pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('sona_ID'){
                  
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Baseleba_geo_app'
                }
               
            }
        }
        stage("maven1"){
            steps{
                sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP75C97147qfehuSCezTx69zJ1D -T \
                 target/geo*.jar \
                 "http://54.236.26.60:8081/artifactory/Geo_App/geo/bio_${BUILD_ID}.jar"'
            }
        }
    }
}