pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('sona_ID'){
                  
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Baseleba_geo_app'
                }
               
            }
        }
        stage("maven1"){
            steps{
                sh 'mvn clean '
                sh 'mvn validate'
                sh 'mvn compile' 
                sh 'mvn install' 
                sh 'mvn test'
                sh 'mvn package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP75C97147qfehuSCezTx69zJ1D -T \
                 target/geo*.jar \
                 "http://54.237.100.134:8081/artifactory/Geo_App/geo/bio_${BUILD_ID}.jar"'
            }
        }
            stage('docker login'){
        steps{
            sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 122403657644.dkr.ecr.us-east-1.amazonaws.com'
        }
    }
    stage('docker image build'){
        steps{
            sh 'docker build -t utc-app-dev:v.${BUILD_ID} .'
            sh 'docker build -t utc-app-dev .'
        }
    }
    stage('Image tagging'){
        steps{
            sh 'docker tag utc-app-dev:v.${BUILD_ID} \
            122403657644.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
            sh 'docker tag utc-app-dev:latest 122403657644.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'

        }
    }
    stage('push image'){
        steps{  
        sh 'docker push 122403657644.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
        sh 'docker push 122403657644.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
    }
    }
    }
}