pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage("maven1"){
            steps{
                sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP75C97147qfehuSCezTx69zJ1D -T \
                 target/Geo*.jar \
                 "http://54.236.26.60:8081/artifactory/Geo_App/geo/bio_${BUILD_ID}.jar"'
            }
        }
    }
}